language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops-jax
  api_key:
    secure: ZL44NNCyrxE+1a3BdEzb8prRPVu3N6qYA5upai6Wm7pZPLTRU+7VSXXSeZVm9H2X+eqk8fQq0NrwgxwO8WCbEwQKTytNs5jbZLxYYnmvQzskFRUtnt6ZslK+mM4eMTfTei4reie6o5lyYx43ILDh4xIlRgGJiO9izOqJE/XDymBsYy1VZJgw510Ka6xmcFkZ/blBIJ4MR+F3kQ1u6kph2zm1+QuDC7idEEl2Y/wwKfObtzD4mzU2dEWivEksM7NUhdMMb1hkXKv5EkhtvxF7VECNQ9czvyxNosz3Wio5qKIinwFNqSrcSMOg2glEgA+deRMNGxwCcKfhCtaxWJcaNvV/UVPCGva0ykfTpH26oG/Hlg3SdFykmvB66jjI5xbwq+7urcSn+SuK3m2QOHU3bgrjv9YyoFmV6E/1TVqJ4lT9ijYIpoLhmqll6tQjfMFxcVmPGNDfAAf+ijCqQcDt58VQKV89krvd8fySRg2ocVan10/a0UHE7BnSMONY29L8uovjR8F7rU237Hy89Z17+2ocDFBkAPHILVD2U3L4nDRlSKMGYNl+dKI5RczrsOCc8bYIxuhOu1R1pxGABc6cltkfmZdDMLw7QkDOyRFWKMmR2VI/QBi7vC1sxkC9QbzOQjvejL5Vj1MqEkmdq+DwFpkbBCGSi03Rtp1Dt6snEgI=
