language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: mudar_para_o_nome_de_sua_app_no_heroku
  api_key:
    secure: YnMBdwEZQqLATHilpCiZsyh5NKl8LUUfnsZZypBkUZE96AJ831lTXyXMKlo81Urb69nqXSF52JChykqdySTA402a1jiGpdUqJwaOK72DrW2TnbXpEHiB75Cjjzd95JirlFnmzS6Or+EeWWY8RZ9xEGupfoErkQpCXaiU244sE13m/R45m99H+WPQBMgXN7IHoMfdNfANuMtcDhD4y0xTmsnzptZLrH/+3GG5ve9zjs1NtNmtaoMjWuR0TOVedVcou38kKWr4yuoM/XMDRbTCmFPLMqAZ1SVeLifgjoMjslUOkGtK1GOYtn3s+mZ0/BfWT4ts1/Zxbou6cR/L2z8Hic3ut7rwSQ7IRFJs8L4XkzvGMoXMI9fUm/AkTrmE4334hWO11i18ndfLN4k9NQJ9Dy/8+hhnduVRkXQtyRAYPLx1zFV7SJ7a9rSzS9Dpzw7OXMuRDxO5IlypNlKj+/igd6QgY5eWJYW2I8A/BVlhdHEwtBZzezpcw5k1cR6A8ImdHAHr9UzDtRrl6YE8NE0Rec2xWggt2nEmjphlR2/Fo3AIyYdF3qcJmvYROUqAyGV85OMNJueXXYMEu6EJWoVFq6G7F3OeQRevKnxZUaL3dorPTFTmg0wzNvzUiVsTR2Cx/9+vGG7sr8mPH0DMX+f+SfmiCY24QXEHukyogaVd5zE=
